### ISSUE TITLE
Wave visual editor Build error

### ISSUE THREAD

**Issue by MarioMeldau** [EvergineTeam/Feedback#25] opened 2020-08-31 15:27 UTC
@vicfergar 

Hello,

in the wave visual editor when i like to build the project i get an error. One dialog with BUILD FAILED appears.  This message is from the console: 31 Aug 2020 17:22:48,153 DEBUG - Analytics | Event not tagged because session is not open.

![build_error](https://user-images.githubusercontent.com/50444578/91737376-49e88200-ebaf-11ea-98bf-7bc665000bf8.png)

**Comment by emepetres** [comment] 2022-01-24 09:32
@MarioMeldau thank you for your feedback and sorry for the late response. Whenever you encounter these type of errors and you are not able to detect the cause from the editor, you can always run the project from Visual Studio which should give you detailed information about the problem.

For a quick responses please check out our [priority support](https://evergine.com/priority-support/)

I'm closing this because we are only giving support for Evergine now, but please feel free to reopen it if you still have the issue.

**Closed by emepetres** 2022-01-24 09:32 UTC
Labels: question
